name = "Outta This World"
author = "UTMG"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d4fca38126a0fb135e2d9df4605fec4d7b2ea49057c6986b2de892d3126a308"

[versions]
fabric = "0.16.4"
minecraft = "1.20.1"
